### ISSUE TITLE
can't modify frozen String

### ISSUE THREAD

**Issue by rachelhanhan** [iamAzeem/fluent-plugin-protobuf-http#8] opened 2021-08-11 01:23 UTC
When I downloaded the plugin and started the fluentd, I keep getting the following error:

```
2021-08-10 18:19:41 -0700 [error]: #0 fluent/log.rb:372:error: unexpected error error_class=FrozenError error="can't modify frozen String"
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/http_server/server.rb:80:in `block (2 levels) in <class:Server>'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluent-plugin-protobuf-http-0.3.0/lib/fluent/plugin/in_protobuf_http.rb:159:in `block in start'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/http_server.rb:70:in `block in http_server_create_http_server'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/http_server/server.rb:51:in `initialize'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/http_server.rb:69:in `new'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/http_server.rb:69:in `http_server_create_http_server'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluent-plugin-protobuf-http-0.3.0/lib/fluent/plugin/in_protobuf_http.rb:158:in `start'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:200:in `block in start'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:189:in `block (2 levels) in lifecycle'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:188:in `each'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:188:in `block in lifecycle'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:175:in `each'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:175:in `lifecycle'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/root_agent.rb:199:in `start'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/engine.rb:248:in `start'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/engine.rb:147:in `run'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:715:in `block in run_worker'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:966:in `main_process'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/supervisor.rb:706:in `run_worker'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/command/fluentd.rb:364:in `<top (required)>'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /Library/Ruby/Gems/2.6.0/gems/fluentd-1.13.3/bin/fluentd:15:in `<top (required)>'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /usr/local/bin/fluentd:23:in `load'
  2021-08-10 18:19:41 -0700 [error]: #0 fluent/supervisor.rb:966:main_process: /usr/local/bin/fluentd:23:in `<main>'
```

Is this a known issue?

**Comment by iamazeem** [comment] 2021-08-11 02:15
Please share the following information to reproduce this:

- Ruby version
- fluentd version
- plugin version
- environment: OS
- command you're using to invoke fluentd
- minimal config

From the logs, looks like you're on a Mac machine with:

- Ruby 2.6.0
- fluentd 1.13.3

Please share the rest of the information.
Thanks!

**Comment by iamazeem** [comment] 2021-08-11 02:42
Just added macos-10.15 in [the CI workflow](https://github.com/iamazeem/fluent-plugin-protobuf-http/blob/bafbb0b4319ce3c691bdfcbcc1b1d57afa0be30a/.github/workflows/ci.yml):

https://github.com/iamazeem/fluent-plugin-protobuf-http/blob/bafbb0b4319ce3c691bdfcbcc1b1d57afa0be30a/.github/workflows/ci.yml#L18

Tested for Ruby versions:

https://github.com/iamazeem/fluent-plugin-protobuf-http/blob/bafbb0b4319ce3c691bdfcbcc1b1d57afa0be30a/.github/workflows/ci.yml#L19

Here's the successful run:
https://github.com/iamazeem/fluent-plugin-protobuf-http/runs/3296452585

Most probably, it's an environment-related issue.
I'll try to reproduce it once I have all the required information from your side.

**Comment by rachelhanhan** [comment] 2021-08-11 05:36
Thanks for the quick reply!
Yes Ruby is 2.6.
Plugin version: fluent-plugin-protobuf-http-0.3.0
Environment: MacOS 11.5.1
Command: fluentd -c fluent/fluent.conf -vv &
fluent.conf:
```
<source>
  @type       protobuf_http
  @id         protobuf_http_input

  bind        0.0.0.0
  port        8080
  tag         debug.test

  proto_dir   fluent/protos
  in_mode     binary
  out_mode    json
</source>
```

**Comment by iamazeem** [comment] 2021-08-11 09:01
Just tested with:

**Environment**

- macOS Big Sur 11.3.1
- protoc 3.17.3
- Ruby 2.6.3p62
- fluentd 1.13.3
- fluent-plugin-protobuf-http 0.3.0

**test.conf**

```
<source>
  @type       protobuf_http
  @id         protobuf_http_input

  bind        0.0.0.0
  port        8080
  tag         debug.test

  proto_dir   fluent/protos
  in_mode     binary
  out_mode    json
</source>
```

**fluent/protos/log.proto**

```
syntax = "proto3";

package service.logging;

import "google/protobuf/timestamp.proto";

message Log {
  message Context {
    google.protobuf.Timestamp timestamp = 1;
    string host_or_ip = 2;
    string service_name = 3;
    string user = 4;
  }

  enum Level {
    DEBUG = 0;
    INFO = 1;
    WARN = 2;
    ERROR = 3;
    FATAL = 4;
  }

  Context context = 1;
  Level level = 2;
  string message = 3;
}
```

And, it worked fine.

**Demo**

![macos-test](https://user-images.githubusercontent.com/7128328/129001976-57657e53-9221-433d-b12f-abdf9e07e70b.gif)

**Comment by rachelhanhan** [comment] 2021-08-12 06:17
Thanks for sharing the demo here!  I still cannot make this work. But if this is not a problem with the plugin, feel free to close the issue.

**Comment by iamazeem** [comment] 2021-08-12 06:30
You're welcome!
Looks like it's not directly related to the plugin.
You can test it on a VM with a clean environment, just to be sure.
Closing it for now.

**Closed as completed by iamazeem** 2021-08-12 06:30 UTC
